const FONT_COLORS = {
    COLOR_PRIMARY_1: "#000000",
    COLOR_PRIMARY_2: "#9112BC",
    COLOR_PRIMARY_3: "#D1D5DB",
    COLOR_PRIMARY_4: "#9CA3AF",
    COLOR_DANGER: "#E62727"
}

const BORDER_COLORS = {
    COLOR_PRIMARY_1: "#9112BC",
    COLOR_PRIMARY_2: "#D3DAD9",
}

const BACKGROUND_COLORS = {
    COLOR_PRIMARY_1: "#FFFFFF",
}

export { FONT_COLORS, BORDER_COLORS, BACKGROUND_COLORS }