spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: yhaddar
    password: 3705
    url: jdbc:postgresql://0.0.0.0:5432/shoes_store
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379
      password: 3705
      repositories:
        enabled: false
  cache:
    type: redis
app:
  server:
    port: 8080
    address: http://localhost