spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: yhaddar
    password: 3705
    url: jdbc:postgresql://0.0.0.0:5432/shoes_store
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379
      password: 3705
      repositories:
        enabled: false
  cache:
    type: redis
  mail:
    host: smtp.gmail.com
    port: 587
    username: youssefhaddar9@gmail.com
    password: mlwhxynkrfcqaupa
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
app:
  server:
    port: 8081
    address: http://localhost
server:
  port: 8081

secret:
  key: u6RZv5D2cG8Zxq1bOZbK1uN2U5K9q3FfV6S8k9pL0sM=
